#!/usr/bin/env python3
"""Render explicit lockfiles from unified lockfiles.

This script takes the unified lockfiles generated by 04-test-conda-lock-with-pkgs.py
and renders them to explicit format for comparison.

For more context, see:
<https://github.com/mamba-org/mamba/issues/4052>
"""

import subprocess
import sys

from pathlib import Path
from typing import Final


SCRIPT_DIR: Final[Path] = Path(__file__).resolve().parent
PLATFORM: Final[str] = "linux-64"


def render_explicit_lockfile(unified_lockfile: Path) -> Path:
    """Render an explicit lockfile from a unified lockfile.

    Args:
        unified_lockfile: Path to the unified lockfile

    Returns:
        Path to the generated explicit lockfile
    """
    # Determine output filename
    # e.g., lockfile-2.1.0-pkgs-lock-with-conda.yml -> lockfile-2.1.0-pkgs-lock-with-conda-explicit.lock
    stem = unified_lockfile.stem  # Remove .yml
    output_file = unified_lockfile.parent / f"{stem}-explicit.lock"

    cmd = [
        "conda-lock",
        "render",
        "--kind=explicit",
        f"--platform={PLATFORM}",
        f"--filename-template={output_file}",
        unified_lockfile,
    ]

    subprocess.run(cmd, check=True, capture_output=False)

    return output_file


def main() -> None:
    """Render all unified lockfiles to explicit format."""
    # Find all unified lockfiles
    pattern = "lockfile-*-lock-with-*.yml"
    lockfiles = sorted(SCRIPT_DIR.glob(pattern))

    if not lockfiles:
        print(f"Error: No lockfiles found matching pattern: {pattern}", file=sys.stderr)
        print("Run: python 04-test-conda-lock-with-pkgs.py first", file=sys.stderr)
        sys.exit(1)

    print(f"Found {len(lockfiles)} unified lockfiles to render")
    print()

    # Render all lockfiles to explicit format
    explicit_lockfiles = []
    for lockfile in lockfiles:
        print(f"Rendering: {lockfile.name}")
        explicit_lockfile = render_explicit_lockfile(lockfile)
        explicit_lockfiles.append(explicit_lockfile)
        print(f"  → {explicit_lockfile.name}")

    print()
    print("=" * 60)
    print("Success!")
    print(f"Rendered {len(explicit_lockfiles)} explicit lockfiles")
    print()
    print("To compare explicit lockfiles, run:")
    print(
        "  diff lockfile-2.1.0-pkgs-lock-with-conda-explicit.lock lockfile-2.1.1-pkgs-lock-with-conda-explicit.lock"
    )
    print(
        "  diff lockfile-2.1.0-pkgs-lock-with-mamba-explicit.lock lockfile-2.1.1-pkgs-lock-with-mamba-explicit.lock"
    )
    print(
        "  diff lockfile-2.1.0-pkgs-lock-with-conda-explicit.lock lockfile-2.3.3-pkgs-lock-with-conda-explicit.lock"
    )
    print(
        "  diff lockfile-2.1.0-pkgs-lock-with-mamba-explicit.lock lockfile-2.3.3-pkgs-lock-with-mamba-explicit.lock"
    )


if __name__ == "__main__":
    main()
