name: mkdocs
on:
  push:
    branches:
      - main
  workflow_dispatch:

# Default to bash in login mode; key to activating conda environment
# https://github.com/mamba-org/provision-with-micromamba#IMPORTANT
defaults:
  run:
    shell: "bash -l {0}"

# Deny all permissions by default
permissions: {}

env:
  MICROMAMBA_VERSION: 'latest'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    permissions:
      contents: write  # for mkdocs gh-deploy to push to gh-pages branch
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: "recursive"
          fetch-depth: 0       # Fetch all history for .GitInfo and .Lastmod
          persist-credentials: true

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Install dependencies
        uses: mamba-org/setup-micromamba@f457c30a868e4760d3a6fcea5f25dc655b8edf39 # v3.2.1
        with:
          micromamba-version: "${{ env.MICROMAMBA_VERSION }}"
          environment-file: "environments/dev-environment.yaml"
          cache-environment: true

      - name: Install conda-lock
        run: "pip install ."

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Deploy with mkdocs
        run: mkdocs gh-deploy --force
