name: typechecks

# Disable default permissions and grant minimal required permissions
permissions: {}

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

defaults:
  run:
    # Ensure activation for micromamba
    shell: bash -leo pipefail {0}

concurrency:
  # Concurrency group that uses the workflow name and PR number if available
  # or commit SHA as a fallback. If a new build is triggered under that
  # concurrency group while a previous build is running it will be canceled.
  # Repeated pushes to a PR will cancel all previous builds, while multiple
  # merges to main will not cancel.
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  typechecks:
    name: ty
    runs-on: ubuntu-latest
    steps:
    # Initialization
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 0
        persist-credentials: false

    - uses: mamba-org/setup-micromamba@f457c30a868e4760d3a6fcea5f25dc655b8edf39 # v3.2.1
      with:
        environment-file: environments/conda-lock.yml
        environment-name: conda-lock-dev
        init-shell: bash
        cache-environment: true
        create-args: >-
          --category=main --category=dev

    - name: Run ty
      run: |
        pre-commit run --verbose --show-diff-on-failure --color=always --all-files ty

    # Upload logs
    - name: Upload pre-commit log
      if: always()
      uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7.0.2
      with:
        name: pre-commit-ty.log
        path: /home/runner/.cache/pre-commit/pre-commit.log
