name: Run conda-lock to update dependencies

# Disable default permissions and grant minimal required permissions
permissions: {}

on:
  workflow_dispatch:
  schedule:
  # At 5:28am UTC Monday and Thursday
  - cron: 28 5 * * MON,THU

jobs:
  create-lockfiles:
    name: create-lockfiles
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.14" ]

    # Don't run scheduled job on forks. Ref: <https://github.com/orgs/community/discussions/26684#discussioncomment-3252843>
    if: (github.event_name == 'schedule' && github.repository == 'conda/conda-lock') || (github.event_name != 'schedule')
    defaults:
      run:
        # Ensure the environment is activated
        # <https://github.com/mamba-org/provision-with-micromamba#important>
        shell: bash -l {0}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write  # for uploading artifacts
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Install Micromamba
      uses: mamba-org/setup-micromamba@f457c30a868e4760d3a6fcea5f25dc655b8edf39 # v3.2.1
      with:
        environment-file: environments/conda-lock.yml
        environment-name: conda-lock-dev

    - name: Install conda-lock from branch
      run: pip install --editable .

    - name: Run conda-lock to recreate lockfile from scratch
      run: |
        export PYTHON_VERSION=${PY_VER}
        source scripts/update_lockfile.sh
      env:
        PY_VER: ${{ matrix.python-version }}

    - name: Upload lockfile
      uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7.0.2
      with:
        name: conda-lock-python-${{ matrix.python-version }}-${{ github.run_id }}-${{ github.run_attempt }}
        path: environments/conda-lock-python-${{ matrix.python-version }}.yaml

  update-pixi:
    name: update-pixi
    if: (github.event_name == 'schedule' && github.repository == 'conda/conda-lock') || (github.event_name != 'schedule')
    defaults:
      run:
        # Ensure the environment is activated
        # <https://github.com/mamba-org/provision-with-micromamba#important>
        shell: bash -l {0}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write  # for uploading artifacts
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Install Micromamba
      uses: mamba-org/setup-micromamba@f457c30a868e4760d3a6fcea5f25dc655b8edf39 # v3.2.1
      with:
        environment-file: environments/conda-lock.yml
        environment-name: conda-lock-dev

    - name: Install pixi
      run: micromamba install pixi --yes

    - name: Install conda-lock from branch
      run: pip install --editable .

    - name: Run conda-lock to recreate lockfile from scratch
      run: |
        source scripts/generate_pixi.sh

    - name: Upload pixi.toml
      uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7.0.2
      with:
        name: pixi.toml-${{ github.run_id }}-${{ github.run_attempt }}
        path: pixi.toml

    - name: Upload pixi.lock
      uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7.0.2
      with:
        name: pixi.lock-${{ github.run_id }}-${{ github.run_attempt }}
        path: pixi.lock

  create-pr:
    name: create-pr
    needs:
      - create-lockfiles
      - update-pixi
    runs-on: ubuntu-latest
    permissions:
      contents: write     # for creating pull requests
      pull-requests: write # for creating pull requests
      actions: read       # for downloading artifacts
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - name: Download all lockfiles
      uses: actions/download-artifact@9000827ccba6bdab643e8b6fd33ac0654aef8333 # v8.0.2
      with:
        pattern: conda-lock-python-*-${{ github.run_id }}-${{ github.run_attempt }}
        path: environments/
        merge-multiple: true

    - name: Download all pixi files
      uses: actions/download-artifact@9000827ccba6bdab643e8b6fd33ac0654aef8333 # v8.0.2
      with:
        pattern: pixi.*-${{ github.run_id }}-${{ github.run_attempt }}
        path: .
        merge-multiple: true

    - name: Open a pull request
      uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
      with:
        # # The default GITHUB_TOKEN doesn't allow other workflows to trigger.
        # # Thus if there are tests to be run, they won't be run. For more info,
        # # see the note under
        # # <https://github.com/peter-evans/create-pull-request#action-inputs>.
        # # One possible workaround is to specify a Personal Access Token (PAT).
        # # This PAT should have read-write permissions for "Pull Requests"
        # # and read-write permissions for "Contents".
        token: ${{ secrets.GH_PAT_FOR_PR_2 }}
        commit-message: Relock dependencies
        title: Relock dependencies
        body: >
          This pull request relocks the dependencies with conda-lock.
          It is triggered by [update-lockfile](https://github.com/conda/conda-lock/blob/main/.github/workflows/update-lockfile.yaml).
        branch: relock-deps
        labels: conda-lock
        delete-branch: true
